name: Build and push Frontend and Backend Images

on:
  push

jobs:
  build_and_publish:
    name: Build Docker image and push to repositories
    runs-on: ubuntu-latest
    steps:  
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Github Packages
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: safeeha
          password: ${{ secrets.GH_PAT }}
      
      - name: Build and push backend image
        uses: docker/build-push-action@v2
        with:
            context: ./server
            file: ./server/Dockerfile
            tags: ghcr.io/safeeha/backend:latest
            push: ${{ github.ref == 'refs/heads/main' }}

      - name: Build and push frontend image
        uses: docker/build-push-action@v2
        with:
              context: ./public
              file: ./public/Dockerfile
              tags: ghcr.io/safeeha/frontend:latest
              push: ${{ github.ref == 'refs/heads/main' }}      